import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    // Layout
    "flex",
    "flex-col",
    "flex-row",
    "flex-wrap",
    "flex-1",
    "flex-shrink-0",
    "grid",
    "grid-cols-1",
    "grid-cols-2",
    "grid-cols-3",
    "grid-cols-4",
    "items-center",
    "items-start",
    "items-end",
    "justify-center",
    "justify-between",
    "justify-start",
    "justify-end",
    "gap-1",
    "gap-2",
    "gap-3",
    "gap-4",
    "gap-6",
    "gap-8",
    "gap-10",
    "gap-12",
    // Spacing
    "p-0",
    "p-1",
    "p-2",
    "p-3",
    "p-4",
    "p-5",
    "p-6",
    "p-8",
    "p-10",
    "p-12",
    "p-16",
    "p-20",
    "px-0",
    "px-1",
    "px-2",
    "px-3",
    "px-4",
    "px-5",
    "px-6",
    "px-8",
    "px-10",
    "px-12",
    "px-16",
    "px-20",
    "py-0",
    "py-1",
    "py-2",
    "py-3",
    "py-4",
    "py-5",
    "py-6",
    "py-8",
    "py-10",
    "py-12",
    "py-16",
    "py-20",
    "py-24",
    "m-0",
    "m-1",
    "m-2",
    "m-3",
    "m-4",
    "m-auto",
    "mx-auto",
    "my-2",
    "my-4",
    "my-6",
    "my-8",
    "mt-0",
    "mt-1",
    "mt-2",
    "mt-4",
    "mt-6",
    "mt-8",
    "mt-10",
    "mt-12",
    "mt-16",
    "mb-0",
    "mb-1",
    "mb-2",
    "mb-4",
    "mb-6",
    "mb-8",
    "mb-10",
    "mb-12",
    "mb-16",
    "ml-0",
    "ml-1",
    "ml-2",
    "ml-4",
    "ml-auto",
    "mr-0",
    "mr-1",
    "mr-2",
    "mr-4",
    "mr-auto",
    "space-x-1",
    "space-x-2",
    "space-x-3",
    "space-x-4",
    "space-y-1",
    "space-y-2",
    "space-y-4",
    "space-y-6",
    "space-y-8",
    // Sizing
    "w-full",
    "w-auto",
    "w-1/2",
    "w-1/3",
    "w-2/3",
    "w-1/4",
    "w-3/4",
    "w-screen",
    "w-4",
    "w-5",
    "w-6",
    "w-8",
    "w-10",
    "w-12",
    "w-16",
    "w-20",
    "w-24",
    "w-32",
    "w-40",
    "w-48",
    "w-64",
    "h-full",
    "h-auto",
    "h-screen",
    "h-4",
    "h-5",
    "h-6",
    "h-8",
    "h-10",
    "h-12",
    "h-14",
    "h-16",
    "h-20",
    "h-24",
    "h-32",
    "h-40",
    "h-48",
    "h-64",
    "min-h-screen",
    "min-h-full",
    "min-w-0",
    "max-w-xs",
    "max-w-sm",
    "max-w-md",
    "max-w-lg",
    "max-w-xl",
    "max-w-2xl",
    "max-w-3xl",
    "max-w-4xl",
    "max-w-5xl",
    "max-w-6xl",
    "max-w-7xl",
    "max-w-full",
    "max-w-screen-xl",
    // Position
    "relative",
    "absolute",
    "fixed",
    "sticky",
    "inset-0",
    "top-0",
    "top-4",
    "right-0",
    "right-4",
    "bottom-0",
    "bottom-4",
    "left-0",
    "left-4",
    "z-10",
    "z-20",
    "z-30",
    "z-40",
    "z-50",
    // Display
    "block",
    "inline-block",
    "inline",
    "hidden",
    "overflow-hidden",
    "overflow-x-auto",
    "overflow-y-auto",
    // Typography
    "text-xs",
    "text-sm",
    "text-base",
    "text-lg",
    "text-xl",
    "text-2xl",
    "text-3xl",
    "text-4xl",
    "text-5xl",
    "font-normal",
    "font-medium",
    "font-semibold",
    "font-bold",
    "text-left",
    "text-center",
    "text-right",
    "leading-tight",
    "leading-normal",
    "leading-relaxed",
    "tracking-tight",
    "tracking-normal",
    "tracking-wide",
    "uppercase",
    "lowercase",
    "capitalize",
    "truncate",
    "whitespace-nowrap",
    // Colors
    "text-white",
    "text-black",
    "text-gray-100",
    "text-gray-200",
    "text-gray-300",
    "text-gray-400",
    "text-gray-500",
    "text-gray-600",
    "text-gray-700",
    "text-gray-800",
    "text-gray-900",
    "text-primary",
    "text-primary-foreground",
    "bg-white",
    "bg-black",
    "bg-transparent",
    "bg-gray-50",
    "bg-gray-100",
    "bg-gray-200",
    "bg-gray-300",
    "bg-gray-400",
    "bg-gray-500",
    "bg-gray-600",
    "bg-gray-700",
    "bg-gray-800",
    "bg-gray-900",
    "bg-dark-background",
    "bg-dark-card",
    "bg-dark-muted",
    // Borders
    "border",
    "border-0",
    "border-2",
    "border-4",
    "border-t",
    "border-b",
    "border-l",
    "border-r",
    "border-gray-200",
    "border-gray-300",
    "border-gray-600",
    "border-gray-700",
    "border-dark-border",
    "border-primary",
    "rounded",
    "rounded-sm",
    "rounded-md",
    "rounded-lg",
    "rounded-xl",
    "rounded-2xl",
    "rounded-full",
    "rounded-none",
    // Effects
    "shadow",
    "shadow-sm",
    "shadow-md",
    "shadow-lg",
    "shadow-xl",
    "shadow-2xl",
    "shadow-none",
    "opacity-0",
    "opacity-25",
    "opacity-50",
    "opacity-75",
    "opacity-100",
    "transition",
    "transition-all",
    "transition-colors",
    "transition-opacity",
    "transition-transform",
    "duration-150",
    "duration-200",
    "duration-300",
    "duration-500",
    "ease-in",
    "ease-out",
    "ease-in-out",
    "hover:opacity-80",
    "hover:opacity-100",
    "hover:scale-105",
    "hover:bg-gray-100",
    "hover:bg-gray-700",
    "hover:bg-dark-muted",
    "hover:text-primary",
    "hover:border-primary",
    "transform",
    "scale-100",
    "scale-105",
    "scale-110",
    // Responsive
    "sm:flex",
    "sm:grid",
    "sm:hidden",
    "sm:block",
    "sm:flex-row",
    "sm:grid-cols-2",
    "sm:text-left",
    "md:flex",
    "md:grid",
    "md:hidden",
    "md:block",
    "md:flex-row",
    "md:grid-cols-2",
    "md:grid-cols-3",
    "md:grid-cols-4",
    "md:text-lg",
    "md:text-xl",
    "md:text-2xl",
    "md:text-4xl",
    "md:p-8",
    "md:px-8",
    "md:py-16",
    "lg:flex",
    "lg:grid",
    "lg:hidden",
    "lg:block",
    "lg:flex-row",
    "lg:grid-cols-3",
    "lg:grid-cols-4",
    "lg:grid-cols-5",
    "lg:text-xl",
    "lg:text-5xl",
    "lg:p-12",
    "lg:px-12",
    "xl:grid-cols-5",
    "xl:grid-cols-6",
    // Dark mode
    "dark:text-white",
    "dark:text-gray-100",
    "dark:text-gray-200",
    "dark:text-gray-300",
    "dark:text-gray-400",
    "dark:bg-dark-background",
    "dark:bg-dark-card",
    "dark:bg-dark-muted",
    "dark:bg-gray-800",
    "dark:bg-gray-900",
    "dark:border-gray-600",
    "dark:border-gray-700",
    "dark:border-dark-border",
    "dark:hover:bg-dark-muted",
    "dark:hover:bg-gray-700",
    // Container
    "container",
    "mx-auto",
    // Images
    "object-contain",
    "object-cover",
    "object-center",
    // Cursor & interaction
    "cursor-pointer",
    "pointer-events-none",
    "select-none",
    // Animation
    "animate-pulse",
    "animate-spin",
    // Group
    "group",
    "group-hover:opacity-100",
    "group-hover:scale-105",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#ccb699",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        dark: {
          background: "#222222",
          foreground: "#ffffff",
          card: "#2a2a2a",
          muted: "#333333",
          border: "#444444",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}

export default config
